9614652:  # Date Annotator
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200  # in seconds
  # question: Date Annotator
  submit_to:
    - "9614719"  # MCW
  center: SAGEBIO
  submission_viewid: syn23747126
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: false
  # goldstandard: null
9614654:  # Date Annotator - Test
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Date Annotator
  submit_to:
    - "9614719"  # MCW
    - "9614757"  # SAGEBIO Test
  center: SAGEBIO
  submission_viewid: syn23512270
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: true
  # goldstandard: null
9614657:  # Person Name Annotator
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Person Name Annotator
  submit_to:
    - "9614720"  # MCW
  center: SAGEBIO
  submission_viewid: syn23747126
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: false
  # goldstandard: null
9614685:  # Person Name Annotator - Test
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Person Name Annotator
  submit_to:
    - "9614720"  # MCW
  center: SAGEBIO
  submission_viewid: syn23512270
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: true
  # goldstandard: null
9614658:  # Physical Address Annotator
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to:
    - "9614721"  # MCW
  center: SAGEBIO
  submission_viewid: syn23747126
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: false
  # goldstandard: null
9614684: # Physical Address Annotator - Test
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to:
    - "9614721"  # MCW
  center: SAGEBIO
  submission_viewid: syn23512270
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: true
  # goldstandard: null
9614799:  # Contact Annotator
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Contact Annotator
  submit_to:
    - "9614804"  # MCW
  center: SAGEBIO
  submission_viewid: syn23747126
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: false
  # goldstandard: null
9614800: # Contact Annotator - Test
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Contact Annotator
  submit_to:
    - "9614804"  # MCW
  center: SAGEBIO
  submission_viewid: syn23512270
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: true
  # goldstandard: null
9614797:  # Id Annotator
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Id Annotator
  submit_to:
    - "9614803"  # MCW
  center: SAGEBIO
  submission_viewid: syn23747126
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: false
  # goldstandard: null
9614798: # Id Annotator - Test
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Id Annotator
  submit_to:
    - "9614803"  # MCW
  center: SAGEBIO
  submission_viewid: syn23512270
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: true
  # goldstandard: null
9614757: # SAGEBIO - Date Annotator Test Internal
  dataset_name: i2b2-phi
  dataset_version: "20210606"
  runtime: 7200
  # question: Date Annotator
  submit_to: null
  center: SAGEBIO
  submission_viewid: syn25584929
  datanode_endpoint: http://10.255.21.50/api/v1/
  # test: false
  # goldstandard: null
9614719: # MCW - Date Annotator
  dataset_name: mcw-phi
  dataset_version: "20210608"
  runtime: 7200
  # question: Date Annotator
  submit_to: null
  center: MCW
  submission_viewid: syn25582644
  datanode_endpoint: http://141.106.224.48:8080/api/v1/
  # test: false
  # goldstandard: null
9614720: # MCW - Person Name Annotator
  dataset_name: mcw-phi
  dataset_version: "20210608"
  runtime: 7200
  # question: Person Name Annotator
  submit_to: null
  center: MCW
  submission_viewid: syn25582644
  datanode_endpoint: http://141.106.224.48:8080/api/v1/
  # test: false
  # goldstandard: null
9614721: # MCW - Physical Address Annotator
  dataset_name: mcw-phi
  dataset_version: "20210608"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to: null
  center: MCW
  submission_viewid: syn25582644
  datanode_endpoint: http://141.106.224.48:8080/api/v1/
  # test: false
  # goldstandard: null
9614804: # MCW - Contact Annotator
  dataset_name: mcw-phi
  dataset_version: "20210608"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to: null
  center: MCW
  submission_viewid: syn25582644
  datanode_endpoint: http://141.106.224.48:8080/api/v1/
  # test: false
  # goldstandard: null
9614803: # MCW - Id Annotator
  dataset_name: mcw-phi
  dataset_version: "20210608"
  runtime: 7200
  # question: Physical Address Annotator
  submit_to: null
  center: MCW
  submission_viewid: syn25582644
  datanode_endpoint: http://141.106.224.48:8080/api/v1/
  # test: false
  # goldstandard: null